# Generated by Django 4.2.3 on 2023-07-30 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_exp_report"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Exp",
        ),
        migrations.RemoveField(
            model_name="businesshours",
            name="end_time_local",
        ),
        migrations.RemoveField(
            model_name="businesshours",
            name="start_time_local",
        ),
        migrations.AddField(
            model_name="businesshours",
            name="end_time_utc",
            field=models.TimeField(default=datetime.time(23, 59, 59)),
        ),
        migrations.AddField(
            model_name="businesshours",
            name="start_time_utc",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="status",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
